/* --- triage:lib start --- */
/* Pure, DOM-free logic for the Incident Triage console.
 *
 * This file is the source of truth. The copy inlined into prototype.html is
 * generated by `node frontend/sync-lib.mjs`, so that the prototype stays a
 * single self-contained file you can open from disk while this logic stays
 * unit-testable. `node --test frontend/test/` fails if the two drift apart.
 */

/* SLA budgets come straight from the BRD's non-functional requirements. */
var SLA_BUDGET_MS = 5 * 60 * 1000; /* NFR-01: runbook delivered within 5 min */
var SLA_WARN_AT_FRACTION = 0.8; /* warn with a fifth of the budget left */

/* Severity maps onto the badge tones already defined in design/reference.html.
 * Each carries a glyph and a word as well as a colour, so severity is never
 * communicated by colour alone. */
var SEVERITY = {
  SEV1: { label: 'SEV1', tone: 'danger', glyph: '◆', text: 'Critical' },
  SEV2: { label: 'SEV2', tone: 'warning', glyph: '▲', text: 'High' },
  SEV3: { label: 'SEV3', tone: 'neutral', glyph: '●', text: 'Moderate' },
  SEV4: { label: 'SEV4', tone: 'neutral', glyph: '○', text: 'Low' }
};

var SEVERITY_ALIASES = {
  critical: 'SEV1', p1: 'SEV1', sev1: 'SEV1',
  high: 'SEV2', major: 'SEV2', p2: 'SEV2', sev2: 'SEV2',
  moderate: 'SEV3', medium: 'SEV3', warning: 'SEV3', p3: 'SEV3', sev3: 'SEV3',
  low: 'SEV4', minor: 'SEV4', info: 'SEV4', p4: 'SEV4', sev4: 'SEV4'
};

function severityMeta(severity) {
  var key = String(severity == null ? '' : severity).trim().toLowerCase();
  var resolved = SEVERITY_ALIASES[key];
  if (resolved) return SEVERITY[resolved];
  return { label: 'UNKNOWN', tone: 'neutral', glyph: '○', text: 'Unclassified' };
}

/* Approval / execution state, mapped onto existing badge tones.
 *
 * These are two separate facts on the runbook row and the map covers both, because
 * a single badge renders whichever one the caller has. `approval_status` records
 * the human decision (pending / approved / declined); `execution_status` records
 * what the remediation platform did (not_started / in_progress / succeeded /
 * failed / skipped).
 *
 * The map used to carry `executed`, which no handler emits, and had no entry for
 * any of the five execution_status values that are actually written -- so a
 * successfully executed remediation rendered as "Unknown". */
var APPROVAL = {
  /* approval_status */
  pending: { tone: 'warning', glyph: '○', text: 'Awaiting approval' },
  approved: { tone: 'neutral', glyph: '◐', text: 'Approved, executing' },
  declined: { tone: 'neutral', glyph: '—', text: 'Declined' },
  /* execution_status */
  not_started: { tone: 'idle', glyph: '·', text: 'Not started' },
  in_progress: { tone: 'neutral', glyph: '◐', text: 'Executing' },
  succeeded: { tone: 'success', glyph: '✓', text: 'Executed' },
  failed: { tone: 'danger', glyph: '✕', text: 'Execution failed' },
  /* C-02 again: no remediation platform configured is not a failure, but it is
   * not success either -- someone still has to run the runbook by hand. */
  skipped: { tone: 'warning', glyph: '⊘', text: 'Not executed — no platform configured' }
};

function approvalMeta(status) {
  var key = String(status == null ? '' : status).trim().toLowerCase();
  return APPROVAL[key] || { tone: 'neutral', glyph: '○', text: 'Unknown' };
}

/* Pipeline stages mirror the Step Functions state machine in spec/design.md. */
var STAGE_TONES = {
  pending: 'idle',
  running: 'active',
  done: 'success',
  failed: 'danger',
  skipped: 'warning'
};

function stageTone(status) {
  return STAGE_TONES[String(status)] || 'idle';
}

/* A stage that is skipped still counts as resolved: C-02 says config data may
 * simply not be available from a tenant's VCS, and that is not a failure. */
function pipelineProgress(stages) {
  if (!Array.isArray(stages) || stages.length === 0) return 0;
  var resolved = 0;
  for (var i = 0; i < stages.length; i++) {
    var status = stages[i] && stages[i].status;
    if (status === 'done' || status === 'skipped' || status === 'failed') resolved++;
  }
  return resolved / stages.length;
}

function pipelineIsComplete(stages) {
  return pipelineProgress(stages) === 1;
}

function pipelineHasFailure(stages) {
  if (!Array.isArray(stages)) return false;
  return stages.some(function (s) { return s && s.status === 'failed'; });
}

/* mm:ss, or h:mm:ss once past an hour. Negative and non-finite clamp to 0:00 so
 * a clock skew never renders "-1:-3". */
function formatElapsed(ms) {
  var total = Number(ms);
  if (!isFinite(total) || total < 0) total = 0;
  var seconds = Math.floor(total / 1000);
  var hours = Math.floor(seconds / 3600);
  var minutes = Math.floor((seconds % 3600) / 60);
  var secs = seconds % 60;
  var pad = function (n) { return n < 10 ? '0' + n : String(n); };
  if (hours > 0) return hours + ':' + pad(minutes) + ':' + pad(secs);
  return minutes + ':' + pad(secs);
}

/* The SLA budget bar. Tone escalates as the 5-minute budget is spent, so a
 * long-running pipeline reads as "still fine" or "about to breach" at a glance
 * rather than as an undifferentiated spinner. */
function slaState(elapsedMs, budgetMs) {
  var budget = Number(budgetMs);
  if (!isFinite(budget) || budget <= 0) budget = SLA_BUDGET_MS;
  var elapsed = Number(elapsedMs);
  if (!isFinite(elapsed) || elapsed < 0) elapsed = 0;

  /* One rule for every budget. The special case this replaces computed the
     same number twice over: 4:00 is exactly 0.8 x 5:00. */
  var warnAt = budget * SLA_WARN_AT_FRACTION;
  var tone = 'ok';
  if (elapsed > budget) tone = 'danger';
  else if (elapsed >= warnAt) tone = 'warning';

  return {
    pct: Math.max(0, Math.min(100, (elapsed / budget) * 100)),
    tone: tone,
    breached: elapsed > budget,
    remainingMs: Math.max(0, budget - elapsed),
    budgetMs: budget
  };
}

/* Authorisation. Requirement 7 gives approval authority to TenantAdmin alone.
 * The UI asks this before rendering the button so a non-admin sees a disabled
 * control with a reason, rather than clicking into a 403. */
var APPROVER_GROUP = 'TenantAdmin';
var KNOWN_ROLES = ['TenantAdmin', 'TenantEngineer', 'TenantLeadership'];

function canApprove(role) {
  return String(role) === APPROVER_GROUP;
}

function approvalBlockReason(role) {
  if (canApprove(role)) return null;
  if (KNOWN_ROLES.indexOf(String(role)) !== -1) {
    return 'Approval is restricted to Tenant Admins. Ask an admin on your team to review and approve this runbook.';
  }
  return 'Your session does not carry a recognised role. Sign in again to approve remediation.';
}

/* Tenant isolation (Requirement 6.3 / C-01). The client refuses to render a
 * resource whose tenant does not match the session, so a mis-scoped API
 * response surfaces as a visible denial instead of leaking across tenants. */
function isTenantMatch(sessionTenantId, resourceTenantId) {
  if (!sessionTenantId || !resourceTenantId) return false;
  return String(sessionTenantId) === String(resourceTenantId);
}

/* Identifiers the user might paste or type. */
function extractIds(text) {
  var source = String(text == null ? '' : text);
  var alerts = source.match(/\bALT-\d{3,}\b/gi) || [];
  var runbooks = source.match(/\bRB-\d{3,}\b/gi) || [];
  var upper = function (s) { return s.toUpperCase(); };
  return { alertIds: alerts.map(upper), runbookIds: runbooks.map(upper) };
}

/* Intent routing.
 *
 * In production this is Bedrock tool-use inside fn-chat; here it stands in for
 * the model and also drives the prototype. `approve` is deliberately NOT an
 * executable intent: it resolves to `focus_approval`, which scrolls to the
 * approval card and focuses it. Typed text never triggers remediation. */
function routeIntent(text) {
  var raw = String(text == null ? '' : text).trim();
  var q = raw.toLowerCase();
  var ids = extractIds(raw);
  var params = {};
  if (ids.alertIds.length) params.alertId = ids.alertIds[0];
  if (ids.runbookIds.length) params.runbookId = ids.runbookIds[0];

  if (!q) return { intent: 'noop', params: params };

  /* Safety first: anything that smells like an approval command is routed to
   * the card, never to an action. */
  if (/\b(approve|authorise|authorize|execute|run it|go ahead|do it|ship it)\b/.test(q)) {
    return { intent: 'focus_approval', params: params };
  }
  if (/\b(decline|reject|cancel|abort|don't|stop)\b/.test(q)) {
    return { intent: 'focus_approval', params: params };
  }
  if (/\b(runbook|step|remediat|fix|playbook)/.test(q)) {
    return { intent: 'show_runbook', params: params };
  }
  if (/\b(chang|commit|deploy|diff|git|release|rollback|rolled back)/.test(q)) {
    return { intent: 'show_changes', params: params };
  }
  if (/\b(log|trace|stack|error|exception|throw)/.test(q)) {
    return { intent: 'show_logs', params: params };
  }
  if (/\b(audit|who approved|history|trail)/.test(q)) {
    return { intent: 'show_audit', params: params };
  }
  if (/\b(status|progress|how long|eta|done yet|finished)/.test(q)) {
    return { intent: 'pipeline_status', params: params };
  }
  if (/\b(list|open|active|incident|alert)\b|what(?:'s| is| are)? *(going on|broken|happening|down|failing|on fire)/.test(q)) {
    return { intent: 'list_incidents', params: params };
  }
  if (/\b(why|root cause|what happened|cause|diagnos|rca)/.test(q)) {
    return { intent: 'show_diagnosis', params: params };
  }
  if (/\b(export|download|json|api)/.test(q)) {
    return { intent: 'export_runbook', params: params };
  }
  if (/\b(help|what can you|how do i)/.test(q)) {
    return { intent: 'help', params: params };
  }
  if (params.alertId || params.runbookId) {
    return { intent: 'show_diagnosis', params: params };
  }
  return { intent: 'unknown', params: params };
}

/* Redaction for anything echoed out of a customer's logs.
 *
 * docs/brd.md flags application logs as possibly containing usernames, session
 * IDs and request data. IPs keep their first two octets because an operator
 * genuinely needs to know which subnet a host sits in. */
function redact(text) {
  return String(text == null ? '' : text)
    .replace(/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g, '‹redacted:email›')
    .replace(/\b(AKIA|ASIA)[0-9A-Z]{16}\b/g, '‹redacted:aws-key›')
    .replace(/\b(bearer|token|authorization)\s*[:=]?\s*[A-Za-z0-9._~+/-]{12,}=*/gi, '‹redacted:credential›')
    .replace(/\b([0-9]{1,3}\.[0-9]{1,3})\.[0-9]{1,3}\.[0-9]{1,3}\b/g, '$1.x.x')
    .replace(/\b[0-9a-f]{32,}\b/gi, '‹redacted:token›');
}

/* Redaction for a whole record's worth of free text.
 *
 * Change history needs this as much as log output does: a config diff is the
 * single most likely place a token or a connection string appears, and the
 * Evidence panel tells the operator that everything in it has been redacted. */
function redactAll(values) {
  return (values || []).map(redact);
}

/* Relative time for the incident rail. Short, because the rail is narrow. */
function relativeTime(fromMs, nowMs) {
  var now = Number(nowMs);
  if (!isFinite(now)) now = Date.now();
  var delta = now - Number(fromMs);
  if (!isFinite(delta) || delta < 0) delta = 0;
  var mins = Math.floor(delta / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return mins + 'm ago';
  var hours = Math.floor(mins / 60);
  if (hours < 24) return hours + 'h ago';
  var days = Math.floor(hours / 24);
  return days + 'd ago';
}

/* Escaping, because every card renders customer-controlled strings (service
 * names, log lines, commit messages) into the DOM. */
function escapeHtml(value) {
  return String(value == null ? '' : value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
/* Prose that is allowed a little inline emphasis, and nothing else.
 *
 * The narrative fields — the one-line cause, the reasoning paragraphs, the
 * remediation step text — are written with <strong>, <em> and <code> in them,
 * and in the deployed system they arrive from Bedrock rather than from a
 * trusted author. Escaping them wholesale would print the tags; interpolating
 * them raw, which is what the render functions used to do, makes every one of
 * them an injection point for model output.
 *
 * So: escape everything, then re-permit exactly these tags, with no attributes.
 * `<code onclick=...>` stays escaped, because the pattern only matches a tag
 * name followed by an optional slash and the closing bracket. */
var INLINE_TAGS = /&lt;(\/?)(strong|em|code|b|i|br)\s*\/?&gt;/gi;

function richText(value) {
  return escapeHtml(value).replace(INLINE_TAGS, function (match, slash, tag) {
    return '<' + slash + tag.toLowerCase() + '>';
  });
}

/* --- triage:lib end --- */

export {
  SLA_BUDGET_MS,
  SLA_WARN_AT_FRACTION,
  SEVERITY,
  APPROVAL,
  APPROVER_GROUP,
  KNOWN_ROLES,
  severityMeta,
  approvalMeta,
  stageTone,
  pipelineProgress,
  pipelineIsComplete,
  pipelineHasFailure,
  formatElapsed,
  slaState,
  canApprove,
  approvalBlockReason,
  isTenantMatch,
  extractIds,
  routeIntent,
  redact,
  redactAll,
  richText,
  relativeTime,
  escapeHtml
};
