/* --- triage:lib start --- */
/* Pure, DOM-free logic for the Incident Triage console.
 *
 * This file is the source of truth. The copy inlined into prototype.html is
 * generated by `node frontend/sync-lib.mjs`, so that the prototype stays a
 * single self-contained file you can open from disk while this logic stays
 * unit-testable. `node --test frontend/test/` fails if the two drift apart.
 */

/* SLA budgets come straight from the BRD's non-functional requirements. */
var SLA_BUDGET_MS = 5 * 60 * 1000; /* NFR-01: runbook delivered within 5 min */
var SLA_WARN_AT_FRACTION = 0.8; /* warn with a fifth of the budget left */

/* Severity maps onto the badge tones already defined in design/reference.html.
 * Each carries a glyph and a word as well as a colour, so severity is never
 * communicated by colour alone. */
var SEVERITY = {
  SEV1: { label: 'SEV1', tone: 'danger', glyph: '◆', text: 'Critical' },
  SEV2: { label: 'SEV2', tone: 'warning', glyph: '▲', text: 'High' },
  SEV3: { label: 'SEV3', tone: 'neutral', glyph: '●', text: 'Moderate' },
  SEV4: { label: 'SEV4', tone: 'neutral', glyph: '○', text: 'Low' }
};

var SEVERITY_ALIASES = {
  critical: 'SEV1', p1: 'SEV1', sev1: 'SEV1',
  high: 'SEV2', major: 'SEV2', p2: 'SEV2', sev2: 'SEV2',
  moderate: 'SEV3', medium: 'SEV3', warning: 'SEV3', p3: 'SEV3', sev3: 'SEV3',
  low: 'SEV4', minor: 'SEV4', info: 'SEV4', p4: 'SEV4', sev4: 'SEV4'
};

function severityMeta(severity) {
  var key = String(severity == null ? '' : severity).trim().toLowerCase();
  var resolved = SEVERITY_ALIASES[key];
  if (resolved) return SEVERITY[resolved];
  return { label: 'UNKNOWN', tone: 'neutral', glyph: '○', text: 'Unclassified' };
}

/* Approval / execution state, mapped onto existing badge tones.
 *
 * These are two separate facts on the runbook row and the map covers both, because
 * a single badge renders whichever one the caller has. `approval_status` records
 * the human decision (pending / approved / declined); `execution_status` records
 * what the remediation platform did (not_started / in_progress / succeeded /
 * failed / skipped).
 *
 * The map used to carry `executed`, which no handler emits, and had no entry for
 * any of the five execution_status values that are actually written -- so a
 * successfully executed remediation rendered as "Unknown". */
var APPROVAL = {
  /* approval_status */
  pending: { tone: 'warning', glyph: '○', text: 'Awaiting approval' },
  approved: { tone: 'neutral', glyph: '◐', text: 'Approved, executing' },
  declined: { tone: 'neutral', glyph: '—', text: 'Declined' },
  /* execution_status */
  not_started: { tone: 'idle', glyph: '·', text: 'Not started' },
  in_progress: { tone: 'neutral', glyph: '◐', text: 'Executing' },
  succeeded: { tone: 'success', glyph: '✓', text: 'Executed' },
  failed: { tone: 'danger', glyph: '✕', text: 'Execution failed' },
  /* C-02 again: no remediation platform configured is not a failure, but it is
   * not success either -- someone still has to run the runbook by hand. */
  skipped: { tone: 'warning', glyph: '⊘', text: 'Not executed — no platform configured' }
};

function approvalMeta(status) {
  var key = String(status == null ? '' : status).trim().toLowerCase();
  return APPROVAL[key] || { tone: 'neutral', glyph: '○', text: 'Unknown' };
}

/* Pipeline stages mirror the Step Functions state machine in spec/design.md. */
var STAGE_TONES = {
  pending: 'idle',
  running: 'active',
  done: 'success',
  failed: 'danger',
  skipped: 'warning'
};

function stageTone(status) {
  return STAGE_TONES[String(status)] || 'idle';
}

/* A stage that is skipped still counts as resolved: C-02 says config data may
 * simply not be available from a tenant's VCS, and that is not a failure. */
function pipelineProgress(stages) {
  if (!Array.isArray(stages) || stages.length === 0) return 0;
  var resolved = 0;
  for (var i = 0; i < stages.length; i++) {
    var status = stages[i] && stages[i].status;
    if (status === 'done' || status === 'skipped' || status === 'failed') resolved++;
  }
  return resolved / stages.length;
}

function pipelineIsComplete(stages) {
  return pipelineProgress(stages) === 1;
}

function pipelineHasFailure(stages) {
  if (!Array.isArray(stages)) return false;
  return stages.some(function (s) { return s && s.status === 'failed'; });
}

/* mm:ss, or h:mm:ss once past an hour. Negative and non-finite clamp to 0:00 so
 * a clock skew never renders "-1:-3". */
function formatElapsed(ms) {
  var total = Number(ms);
  if (!isFinite(total) || total < 0) total = 0;
  var seconds = Math.floor(total / 1000);
  var hours = Math.floor(seconds / 3600);
  var minutes = Math.floor((seconds % 3600) / 60);
  var secs = seconds % 60;
  var pad = function (n) { return n < 10 ? '0' + n : String(n); };
  if (hours > 0) return hours + ':' + pad(minutes) + ':' + pad(secs);
  return minutes + ':' + pad(secs);
}

/* The SLA budget bar. Tone escalates as the 5-minute budget is spent, so a
 * long-running pipeline reads as "still fine" or "about to breach" at a glance
 * rather than as an undifferentiated spinner. */
function slaState(elapsedMs, budgetMs) {
  var budget = Number(budgetMs);
  if (!isFinite(budget) || budget <= 0) budget = SLA_BUDGET_MS;
  var elapsed = Number(elapsedMs);
  if (!isFinite(elapsed) || elapsed < 0) elapsed = 0;

  /* One rule for every budget. The special case this replaces computed the
     same number twice over: 4:00 is exactly 0.8 x 5:00. */
  var warnAt = budget * SLA_WARN_AT_FRACTION;
  var tone = 'ok';
  if (elapsed > budget) tone = 'danger';
  else if (elapsed >= warnAt) tone = 'warning';

  return {
    pct: Math.max(0, Math.min(100, (elapsed / budget) * 100)),
    tone: tone,
    breached: elapsed > budget,
    remainingMs: Math.max(0, budget - elapsed),
    budgetMs: budget
  };
}

/* Authorisation. Requirement 7 gives approval authority to TenantAdmin alone.
 * The UI asks this before rendering the button so a non-admin sees a disabled
 * control with a reason, rather than clicking into a 403. */
var APPROVER_GROUP = 'TenantAdmin';
var KNOWN_ROLES = ['TenantAdmin', 'TenantEngineer', 'TenantLeadership'];

function canApprove(role) {
  /* Delegates to the capability matrix so this and `can` cannot disagree. */
  return can(role, 'approve_remediation');
}

function approvalBlockReason(role) {
  if (canApprove(role)) return null;
  if (KNOWN_ROLES.indexOf(String(role)) !== -1) {
    return 'Approval is restricted to Tenant Admins. Ask an admin on your team to review and approve this runbook.';
  }
  return 'Your session does not carry a recognised role. Sign in again to approve remediation.';
}

/* Tenant isolation (Requirement 6.3 / C-01). The client refuses to render a
 * resource whose tenant does not match the session, so a mis-scoped API
 * response surfaces as a visible denial instead of leaking across tenants. */
function isTenantMatch(sessionTenantId, resourceTenantId) {
  if (!sessionTenantId || !resourceTenantId) return false;
  return String(sessionTenantId) === String(resourceTenantId);
}

/* Identifiers the user might paste or type. */
function extractIds(text) {
  var source = String(text == null ? '' : text);
  var alerts = source.match(/\bALT-\d{3,}\b/gi) || [];
  var runbooks = source.match(/\bRB-\d{3,}\b/gi) || [];
  var upper = function (s) { return s.toUpperCase(); };
  return { alertIds: alerts.map(upper), runbookIds: runbooks.map(upper) };
}

/* Intent routing.
 *
 * In production this is Bedrock tool-use inside fn-chat; here it stands in for
 * the model and also drives the prototype. `approve` is deliberately NOT an
 * executable intent: it resolves to `focus_approval`, which scrolls to the
 * approval card and focuses it. Typed text never triggers remediation. */
function routeIntent(text) {
  var raw = String(text == null ? '' : text).trim();
  var q = raw.toLowerCase();
  var ids = extractIds(raw);
  var params = {};
  if (ids.alertIds.length) params.alertId = ids.alertIds[0];
  if (ids.runbookIds.length) params.runbookId = ids.runbookIds[0];

  if (!q) return { intent: 'noop', params: params };

  /* Safety first: anything that smells like an approval command is routed to
   * the card, never to an action. */
  if (/\b(approve|authorise|authorize|execute|run it|go ahead|do it|ship it)\b/.test(q)) {
    return { intent: 'focus_approval', params: params };
  }
  if (/\b(decline|reject|cancel|abort|don't|stop)\b/.test(q)) {
    return { intent: 'focus_approval', params: params };
  }
  if (/\b(runbook|step|remediat|fix|playbook)/.test(q)) {
    return { intent: 'show_runbook', params: params };
  }
  if (/\b(chang|commit|deploy|diff|git|release|rollback|rolled back)/.test(q)) {
    return { intent: 'show_changes', params: params };
  }
  if (/\b(log|trace|stack|error|exception|throw)/.test(q)) {
    return { intent: 'show_logs', params: params };
  }
  if (/\b(audit|who approved|history|trail)/.test(q)) {
    return { intent: 'show_audit', params: params };
  }
  if (/\b(status|progress|how long|eta|done yet|finished)/.test(q)) {
    return { intent: 'pipeline_status', params: params };
  }
  if (/\b(list|open|active|incident|alert)\b|what(?:'s| is| are)? *(going on|broken|happening|down|failing|on fire)/.test(q)) {
    return { intent: 'list_incidents', params: params };
  }
  if (/\b(why|root cause|what happened|cause|diagnos|rca)/.test(q)) {
    return { intent: 'show_diagnosis', params: params };
  }
  if (/\b(export|download|json|api)/.test(q)) {
    return { intent: 'export_runbook', params: params };
  }
  if (/\b(help|what can you|how do i)/.test(q)) {
    return { intent: 'help', params: params };
  }
  if (params.alertId || params.runbookId) {
    return { intent: 'show_diagnosis', params: params };
  }
  return { intent: 'unknown', params: params };
}

/* Redaction for anything echoed out of a customer's logs.
 *
 * docs/brd.md flags application logs as possibly containing usernames, session
 * IDs and request data. IPs keep their first two octets because an operator
 * genuinely needs to know which subnet a host sits in. */
function redact(text) {
  return String(text == null ? '' : text)
    .replace(/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g, '‹redacted:email›')
    .replace(/\b(AKIA|ASIA)[0-9A-Z]{16}\b/g, '‹redacted:aws-key›')
    .replace(/\b(bearer|token|authorization)\s*[:=]?\s*[A-Za-z0-9._~+/-]{12,}=*/gi, '‹redacted:credential›')
    .replace(/\b([0-9]{1,3}\.[0-9]{1,3})\.[0-9]{1,3}\.[0-9]{1,3}\b/g, '$1.x.x')
    .replace(/\b[0-9a-f]{32,}\b/gi, '‹redacted:token›');
}

/* Redaction for a whole record's worth of free text.
 *
 * Change history needs this as much as log output does: a config diff is the
 * single most likely place a token or a connection string appears, and the
 * Evidence panel tells the operator that everything in it has been redacted. */
function redactAll(values) {
  return (values || []).map(redact);
}

/* Relative time for the incident rail. Short, because the rail is narrow. */
function relativeTime(fromMs, nowMs) {
  var now = Number(nowMs);
  if (!isFinite(now)) now = Date.now();
  var delta = now - Number(fromMs);
  if (!isFinite(delta) || delta < 0) delta = 0;
  var mins = Math.floor(delta / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return mins + 'm ago';
  var hours = Math.floor(mins / 60);
  if (hours < 24) return hours + 'h ago';
  var days = Math.floor(hours / 24);
  return days + 'd ago';
}

/* Escaping, because every card renders customer-controlled strings (service
 * names, log lines, commit messages) into the DOM. */
function escapeHtml(value) {
  return String(value == null ? '' : value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
/* Prose that is allowed a little inline emphasis, and nothing else.
 *
 * The narrative fields — the one-line cause, the reasoning paragraphs, the
 * remediation step text — are written with <strong>, <em> and <code> in them,
 * and in the deployed system they arrive from Bedrock rather than from a
 * trusted author. Escaping them wholesale would print the tags; interpolating
 * them raw, which is what the render functions used to do, makes every one of
 * them an injection point for model output.
 *
 * So: escape everything, then re-permit exactly these tags, with no attributes.
 * `<code onclick=...>` stays escaped, because the pattern only matches a tag
 * name followed by an optional slash and the closing bracket. */
var INLINE_TAGS = /&lt;(\/?)(strong|em|code|b|i|br)\s*\/?&gt;/gi;

function richText(value) {
  return escapeHtml(value).replace(INLINE_TAGS, function (match, slash, tag) {
    return '<' + slash + tag.toLowerCase() + '>';
  });
}


/* ---------- Role capabilities ----------
 *
 * Mirrors the matrix in src/layer/python/common/rbac.py so the interface can
 * disable a control and explain why, rather than letting someone click into a
 * 403 (design/frontend-design.md section 5).
 *
 * This is NOT authorisation. Every capability is checked again inside the
 * handler, because anything the browser decides the browser can also skip; this
 * copy exists only so the UI can be honest before the request is made.
 * tests/test_rbac_parity.py fails if the two ever disagree. */
var CAPABILITIES = {
  view_incidents: ['TenantAdmin', 'TenantEngineer', 'TenantLeadership'],
  view_diagnosis: ['TenantAdmin', 'TenantEngineer', 'TenantLeadership'],
  view_runbooks: ['TenantAdmin', 'TenantEngineer', 'TenantLeadership'],
  create_incident: ['TenantAdmin', 'TenantEngineer'],
  approve_remediation: ['TenantAdmin'],
  view_audit: ['TenantAdmin', 'TenantLeadership'],
  view_overview: ['TenantAdmin', 'TenantLeadership'],
  view_team: ['TenantAdmin', 'TenantLeadership'],
  manage_integrations: ['TenantAdmin'],
  manage_roles: ['TenantAdmin']
};

var ROLE_LABELS = {
  TenantAdmin: 'Tenant Admins',
  TenantEngineer: 'Tenant Engineers',
  TenantLeadership: 'Tenant Leadership'
};

var ROLE_NAMES = {
  TenantAdmin: 'Admin',
  TenantEngineer: 'Engineer',
  TenantLeadership: 'Leadership'
};

var CAPABILITY_VERBS = {
  view_incidents: 'view incidents',
  view_diagnosis: 'view a diagnosis',
  view_runbooks: 'view runbooks',
  create_incident: 'raise an incident',
  approve_remediation: 'approve remediation',
  view_audit: 'read the audit trail',
  view_overview: 'see the tenant overview',
  view_team: 'see the team',
  manage_integrations: 'view or change integrations',
  manage_roles: "change a teammate's role"
};

/* Throws on an unknown capability rather than returning false: a misspelling
 * that merely denied would disable the control for everyone including admins,
 * and look like a data problem instead of a typo. */
function can(role, capability) {
  var holders = CAPABILITIES[capability];
  if (!holders) throw new Error('unknown capability: ' + capability);
  return holders.indexOf(String(role)) !== -1;
}

function capabilityDenialReason(role, capability) {
  if (can(role, capability)) return null;
  var verb = CAPABILITY_VERBS[capability] || capability.replace(/_/g, ' ');
  if (!ROLE_LABELS[role]) {
    return 'Your session does not carry a recognised role, so you cannot ' + verb +
      '. Sign in again.';
  }
  var holders = CAPABILITIES[capability].map(function (r) { return ROLE_LABELS[r] || r; });
  return 'Only ' + holders.join(' or ') + ' may ' + verb + '.';
}

function roleName(role) {
  return ROLE_NAMES[role] || 'No role';
}

/* ---------- Sign-up input ----------
 *
 * Mirrors common/tenancy.py. Tenancy is derived from the email domain, so a
 * consumer address cannot belong to an organisation. fn-pre-signup refuses these
 * server-side; checking here too means the form can say so before submitting
 * rather than surfacing a Cognito error. */
var PUBLIC_EMAIL_DOMAINS = [
  'gmail.com', 'googlemail.com', 'outlook.com', 'hotmail.com', 'live.com',
  'yahoo.com', 'icloud.com', 'me.com', 'aol.com', 'proton.me', 'protonmail.com',
  'gmx.com', 'mail.com', 'yandex.com', 'zoho.com', 'qq.com'
];

function emailDomain(email) {
  var value = String(email == null ? '' : email).trim();
  var at = value.lastIndexOf('@');
  if (at < 1 || at === value.length - 1) return null;
  return value.slice(at + 1).toLowerCase() || null;
}

function isPublicEmailDomain(email) {
  var domain = emailDomain(email);
  return domain !== null && PUBLIC_EMAIL_DOMAINS.indexOf(domain) !== -1;
}

/* The reason this address cannot be used, or null. */
function signupEmailProblem(email) {
  var domain = emailDomain(email);
  if (domain === null) return 'Enter a valid work email address.';
  if (domain.indexOf('.') === -1) return 'Enter a valid work email address.';
  if (PUBLIC_EMAIL_DOMAINS.indexOf(domain) !== -1) {
    return domain + ' is a personal email provider. Use your work email so your ' +
      'account joins your organisation.';
  }
  return null;
}

/* ---------- Password rules ----------
 *
 * Mirrors Cognito's DEFAULT password policy, which CLAUDE.md requires leaving
 * unchanged. So this mirrors and never adds: a form demanding more than the pool
 * enforces would reject passwords the pool would have accepted, and the person
 * would have no way to discover which rule was ours rather than Cognito's. */
var PASSWORD_MIN_LENGTH = 8;

var PASSWORD_RULES = [
  { id: 'length', text: 'At least ' + PASSWORD_MIN_LENGTH + ' characters',
    test: function (v) { return v.length >= PASSWORD_MIN_LENGTH; } },
  { id: 'lower', text: 'A lowercase letter', test: function (v) { return /[a-z]/.test(v); } },
  { id: 'upper', text: 'An uppercase letter', test: function (v) { return /[A-Z]/.test(v); } },
  { id: 'digit', text: 'A number', test: function (v) { return /[0-9]/.test(v); } },
  /* Cognito's own symbol set. */
  { id: 'symbol', text: 'A symbol',
    test: function (v) { return /[\^$*.\[\]{}()?"!@#%&/\\,><':;|_~`=+\- ]/.test(v); } }
];

function passwordChecklist(password) {
  var value = String(password == null ? '' : password);
  return PASSWORD_RULES.map(function (rule) {
    return { id: rule.id, text: rule.text, met: rule.test(value) };
  });
}

function passwordIsAcceptable(password) {
  return passwordChecklist(password).every(function (item) { return item.met; });
}

/* 0-5, for a meter. Deliberately just "how many rules are met" -- an entropy
 * score would imply a judgement the pool does not actually enforce. */
function passwordStrength(password) {
  return passwordChecklist(password).filter(function (i) { return i.met; }).length;
}

/* ---------- Tenant overview ----------
 *
 * The cross-incident picture for TenantLeadership, computed from what two
 * existing endpoints already return: GET /v1/alerts and GET /v1/runbooks. No new
 * backend aggregation, and nothing here invents a number the API cannot support.
 *
 * The SLA figure is the real NFR-01 measurement: a runbook delivered within five
 * minutes of the alert arriving. An incident with no runbook yet is counted as
 * pending while it is inside the budget and breached once it is past it -- so a
 * pipeline that silently never finished shows up, rather than being omitted for
 * having no runbook to measure. */
function summarise(incidents, runbooks, now) {
  var at = typeof now === 'number' ? now : Date.now();
  var list = Array.isArray(incidents) ? incidents : [];
  var books = Array.isArray(runbooks) ? runbooks : [];

  var byAlert = {};
  books.forEach(function (rb) {
    if (rb && rb.alert_id) byAlert[String(rb.alert_id)] = rb;
  });

  var summary = {
    total: list.length,
    bySeverity: { SEV1: 0, SEV2: 0, SEV3: 0, SEV4: 0, UNKNOWN: 0 },
    raisedByHand: 0,
    diagnosed: 0,
    awaitingRunbook: 0,
    awaitingApproval: 0,
    approved: 0,
    declined: 0,
    executed: 0,
    executionFailed: 0,
    slaMet: 0,
    slaBreached: 0,
    slaPending: 0,
    last24h: 0,
    oldestOpenMs: 0,
    runbookTimesMs: []
  };

  list.forEach(function (incident) {
    var meta = severityMeta(incident && incident.severity);
    var key = meta.label === 'UNKNOWN' ? 'UNKNOWN' : meta.label;
    if (summary.bySeverity[key] === undefined) summary.bySeverity[key] = 0;
    summary.bySeverity[key] += 1;

    if (String(incident && incident.source) === 'console') summary.raisedByHand += 1;

    var receivedMs = Number(incident && incident.received_at) * 1000;
    var ageMs = isFinite(receivedMs) ? at - receivedMs : 0;
    if (isFinite(receivedMs) && ageMs <= 24 * 60 * 60 * 1000) summary.last24h += 1;

    var runbook = byAlert[String(incident && incident.alert_id)];

    if (runbook) {
      summary.diagnosed += 1;

      var generatedMs = Number(runbook.generated_at) * 1000;
      if (isFinite(receivedMs) && isFinite(generatedMs) && generatedMs >= receivedMs) {
        var tookMs = generatedMs - receivedMs;
        summary.runbookTimesMs.push(tookMs);
        if (tookMs <= SLA_BUDGET_MS) summary.slaMet += 1;
        else summary.slaBreached += 1;
      }

      if (runbook.approval_status === 'pending') summary.awaitingApproval += 1;
      if (runbook.approval_status === 'approved') summary.approved += 1;
      if (runbook.approval_status === 'declined') summary.declined += 1;
      if (runbook.execution_status === 'succeeded') summary.executed += 1;
      if (runbook.execution_status === 'failed') summary.executionFailed += 1;
    } else {
      summary.awaitingRunbook += 1;
      /* No runbook yet. Inside the budget it is still pending; past it the
       * budget has been missed whether or not one ever arrives. */
      if (ageMs > SLA_BUDGET_MS) summary.slaBreached += 1;
      else summary.slaPending += 1;
      if (ageMs > summary.oldestOpenMs) summary.oldestOpenMs = ageMs;
    }
  });

  summary.medianRunbookMs = median(summary.runbookTimesMs);
  return summary;
}

function median(values) {
  if (!values.length) return null;
  var sorted = values.slice().sort(function (a, b) { return a - b; });
  var mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : Math.round((sorted[mid - 1] + sorted[mid]) / 2);
}

/* --- triage:lib end --- */

export {
  SLA_BUDGET_MS,
  SLA_WARN_AT_FRACTION,
  SEVERITY,
  APPROVAL,
  APPROVER_GROUP,
  KNOWN_ROLES,
  severityMeta,
  approvalMeta,
  stageTone,
  pipelineProgress,
  pipelineIsComplete,
  pipelineHasFailure,
  formatElapsed,
  slaState,
  canApprove,
  approvalBlockReason,
  CAPABILITIES,
  ROLE_LABELS,
  can,
  capabilityDenialReason,
  roleName,
  PUBLIC_EMAIL_DOMAINS,
  emailDomain,
  isPublicEmailDomain,
  signupEmailProblem,
  PASSWORD_MIN_LENGTH,
  PASSWORD_RULES,
  passwordChecklist,
  passwordIsAcceptable,
  passwordStrength,
  summarise,
  isTenantMatch,
  extractIds,
  routeIntent,
  redact,
  redactAll,
  richText,
  relativeTime,
  escapeHtml
};
